const express = require('express');
const { detectText } = require('../controllers/textController');
const { validateTextInput } = require('../middleware/validation');

const router = express.Router();

/**
 * @swagger
 * /api/detect-text:
 *   post:
 *     summary: Analyze text for AI detection
 *     description: Analyzes the provided text to determine if it was generated by AI or written by a human
 *     tags: [Text Analysis]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/TextAnalysisRequest'
 *     responses:
 *       200:
 *         description: Text analysis completed successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/TextAnalysisResponse'
 *             example:
 *               result:
 *                 isAI: true
 *                 confidence: 85.5
 *                 details: "Analysis completed successfully"
 *       400:
 *         description: Bad request - text is required
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *             example:
 *               error: "Text is required"
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *             example:
 *               error: "Text detection failed"
 *               details: "API request failed"
 */
// POST /detect-text - Analyze text for AI detection
router.post('/detect-text', validateTextInput, detectText);

module.exports = router;
