const aiDetectionService = require('../services/aiDetectionService');

/**
 * @swagger
 * /detect-text:
 *   post:
 *     summary: Analyze text for AI detection
 *     description: Analyzes the provided text to determine if it was generated by AI or written by a human
 *     tags: [Text Analysis]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/TextAnalysisRequest'
 *     responses:
 *       200:
 *         description: Text analysis completed successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/TextAnalysisResponse'
 *             example:
 *               result:
 *                 isAI: true
 *                 confidence: 85.5
 *                 details: "Analysis completed successfully"
 *       400:
 *         description: Bad request - text is required
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *             example:
 *               error: "Text is required"
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *             example:
 *               error: "Text detection failed"
 *               details: "API request failed"
 */
const detectText = async (req, res) => {
  try {
    const { text } = req.body;
    
    if (!text) {
      return res.status(400).json({ error: 'Text is required' });
    }

    const result = await aiDetectionService.analyzeText(text);
    res.json({ result });
  } catch (error) {
    console.error('Text detection error:', error.message);
    res.status(500).json({ 
      error: 'Text detection failed', 
      details: error.message 
    });
  }
};

module.exports = {
  detectText
};
